<a href="https://colab.research.google.com/github/oyasai55/oyasai55.github.io/blob/main/lab_2024/1_pytorch/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 基本的な配列操作

In [1]:
import numpy as np

# 配列の作成
arr = np.array([1, 2, 3, 4, 5])
print("配列:", arr)

# 配列の形状とデータ型
print("形状:", arr.shape)
print("データ型:", arr.dtype)

# 配列の要素にアクセス
print("最初の要素:", arr[0])
print("最後の要素:", arr[-1])

# 配列のスライス
print("最初の3つの要素:", arr[:3])

配列: [1 2 3 4 5]
形状: (5,)
データ型: int64
最初の要素: 1
最後の要素: 5
最初の3つの要素: [1 2 3]


### 配列の数学演算

In [ ]:
import numpy as np

# 配列の作成
arr = np.array([1, 2, 3, 4, 5])

# 配列に対する基本的な数学演算
print("配列に2を加算:", arr + 2)
print("配列を2で乗算:", arr * 2)

# 配列同士の演算
arr2 = np.array([5, 4, 3, 2, 1])
print("配列同士の加算:", arr + arr2)
print("配列同士の積:", arr * arr2)

# 統計関数の使用
print("平均:", np.mean(arr))
print("標準偏差:", np.std(arr))

配列に2を加算: [3 4 5 6 7]
配列を2で乗算: [ 2  4  6  8 10]
配列同士の加算: [6 6 6 6 6]
配列同士の積: [5 8 9 8 5]
平均: 3.0
標準偏差: 1.4142135623730951


### 形状変更と多次元配列

In [ ]:
import numpy as np

# 2次元配列の作成
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("2次元配列:")
print(arr)
print(f"shape: {arr.shape}")

# 配列の形状変更
reshaped = arr.reshape(3, 2)
print("形状変更後の配列")
print(reshaped)
print("shape: ", reshaped.shape)

# 3次元配列の例
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3次元配列")
print(arr_3d)
print("shape: ", arr_3d.shape)

2次元配列:
[[1 2 3]
 [4 5 6]]
shape: (2, 3)
形状変更後の配列
[[1 2]
 [3 4]
 [5 6]]
shape:  (3, 2)
3次元配列
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape:  (2, 2, 2)


## 行列演算

### 基本的な演算

In [ ]:
import numpy as np

# 2x2行列の作成
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("行列A:\n", A)
print("行列B:\n", B)

# 行列の加算
C = A + B
print("行列の加算 (A + B):\n", C)

# 行列の減算
D = A - B
print("行列の減算 (A - B):\n", D)

# スカラー倍
E = 2 * A
print("スカラー倍 (2 * A):\n", E)


行列A:
 [[1 2]
 [3 4]]
行列B:
 [[5 6]
 [7 8]]
行列の加算 (A + B):
 [[ 6  8]
 [10 12]]
行列の減算 (A - B):
 [[-4 -4]
 [-4 -4]]
スカラー倍 (2 * A):
 [[2 4]
 [6 8]]


### 行列積と転置

In [ ]:
# 行列積
F = np.dot(A, B)
print("行列積 (A * B):\n", F)

# 行列の転置
G = A.T
print("行列Aの転置:\n", G)


行列積 (A * B):
 [[19 22]
 [43 50]]
行列Aの転置:
 [[1 3]
 [2 4]]


### 逆行列と行列式

In [ ]:
# 逆行列
H = np.linalg.inv(A)
print("行列Aの逆行列:\n", H)

# 行列式
det_A = np.linalg.det(A)
print("行列Aの行列式:", det_A)


行列Aの逆行列:
 [[-2.   1. ]
 [ 1.5 -0.5]]
行列Aの行列式: -2.0000000000000004


### コサイン類似度

In [ ]:
import numpy as np

v1 = np.array([1, 2, 3])
v2 = np.array([-1, -2, -3])

dot_product = np.dot(v1, v2)
norm_v1 = np.linalg.norm(v1)
norm_v2 = np.linalg.norm(v2)
similarity = dot_product / (norm_v1 * norm_v2)

print("コサイン類似度:", similarity)


コサイン類似度: -1.0
